/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

__attribute__((naked)) void change_sp_to_psp(void)
{

	__asm volatile(".equ SRAM_END, (0x20000000 + ( 128 * 1024))");
	__asm volatile(".equ PSP_START, (SRAM_END - 512) ");
	__asm volatile("LDR R0,=PSP_START");
	__asm volatile("MSR PSP,R0");
	// use the control register to change SPSEL bit
	__asm volatile("MRS R0,CONTROL");
	__asm volatile("ORR R0,R0,#0x02");
	__asm volatile("MSR CONTROL,R0");

	__asm volatile("BX LR");


}
void generate_interrupt()
{
	uint32_t *pSTIR = (uint32_t*)0XE000EF00;
	uint32_t *pISER0 =(uint32_t*)0XE000E100;

	//enable the IRq3 interrupt
	*pISER |=(1 <<3);

	//triggers an interrupt from sw for Irq3
	*pSTIR = (3 & 0x1FF);

}

int main(void)
{
    /* Loop forever */
	change_sp_to_psp();// analyze the stack frame , more importantly the EXEC_Return value (LR(through out), and PC ->(just before exit of the handler))

	printf("Before Interrupt generated -- Thread mode\n");

	generate_interrupt();

	printf("After Interrupt generated -- thread mode\n")

	while(1);

}

void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode : ISR\n");

}
