/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
    /* Loop forever */

	__asm volatile("LDR R0,=#20001000");
	__asm volatile("LDR R1,=#20001004");
	 __asm volatile("LDR R0,[R1]");
	 __asm volatile("LDR R1,[R2]");
	 __asm volatile("ADD R0,R0,R1");
	 __asm volatile("STR R0,[R2]");

	for(;;);
}
